### PR TITLE
PHP 8.4

### PR DESCRIPTION
**Pull request by kagg-design**

### CODE REVIEW

**Comment by kagg-design** [comment]
All tests for 8.0 - 8.3 were green. I'm not sure why tests for 8.4 are failing. It looks like a problem with the uopz extension.

**Comment by lucatume** [comment]
Thanks @kagg-design for the PR, you're on a roll.

Did you use rector to run the updates? 

I will look into the failing tests and update this branch.

**Comment by kagg-design** [comment]
Found something more with

```bash
find . -name "*.php" -not -path "*/vendor/*" -exec php -l {} \;
```

The last changes now.

**Comment by lucatume** [comment]
After some digging, I think the issue lies in [in this issue on the `uopz` extension repository](https://github.com/krakjoe/uopz/pull/185).

I've run into the same issue while building the extension locally, and solved building from the branch in the PR. 
Locally, I could run the failing tests without issues on PHP 8.4.

I will debug further should the issue persist.

**Comment by lucatume** [comment]
Finally able to merge and released in [version `4.4.0`](https://github.com/lucatume/wp-browser/releases/tag/4.4.0)

Thanks again @kagg-design, much appreciated.

**Pull request merged**
