### PR TITLE
Codeception 5 and PHP 8 rewrite

### PR DESCRIPTION
**Pull request by lucatume**
The purpose of this PR is to get the project to a state where it's running correctly on PHP 8.0 and Codeception 5.
Minimal removal, deprecations and refactorings.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Hi!

Thanks for the effort! I'm very interested in seeing Codeception 5 compatibility. Right now, especially interested to see how Composer deps will be installed when CC5 is added to `composer.json`. Was going to make a fork, but found this PR.

**Comment by XedinUnknown** [comment]
@lucatume, I see you are busy working on this, and I'd like to express my appreciation. I'm sure a lot of people are waiting on this, me for one.

**Comment by szepeviktor** [comment]
@lucatume I'd like to help cleaning up `src/` directory to contain only PHP class files from a single namespace.
We could begin with `composer dump-autoload --no-interaction --optimize --strict-psr`
It reports `src/Deprecated/Utils/Map.php`.

---

After removing all OOP files
`grep -Eirl '^\s*(((abstract|final)\s+)?class|interface|trait)\s' src/`
these are the remaining non-class-like files.

```
src/Generators/templates/blog_versions.handlebars
src/Generators/templates/subdomain-htaccess.handlebars
src/Generators/templates/site.handlebars
src/Generators/templates/sitemeta.handlebars
src/Generators/templates/new-blog.handlebars
src/Generators/templates/subfolder-htaccess.handlebars
src/Generators/templates/users.handlebars
src/Generators/templates/signups.handlebars
src/Generators/templates/drop-blog-tables.handlebars
src/Generators/templates/blogs.handlebars
src/Generators/templates/registration_log.handlebars
src/support/wpBootstrap.php
src/Deprecated/deprecated-functions.php
src/MonkeyPatch/dud-file.php
src/Process/Worker/worker-script.php
src/version-4-aliases.php
src/scripts/request.php
src/scripts/support-functions.php
src/scripts/pluggable-functions-override.php
src/scripts/request-script-bootstrap.php
src/scripts/filters.php
```

I know it is hard but could we move them to another directory?
May I suggest a solution for each file?

**Comment by lucatume** [comment]
> I'd like to help cleaning up src/ directory to contain only PHP class files from a single namespace.

The benefit would be for static analysis, right?

I'm still working on the code and some of that will either be moved out or removed completely. I'm partial to the idea, but I need more time to assess what I stil need to avoid wasting time moving things I could just remove.

**Comment by szepeviktor** [comment]
> The benefit would be for static analysis, right?

Yes. And general code hygiene: the PSR-4 autoload directory should be only used for that purpose only. No "surprise" files in `src/`.

**Comment by szepeviktor** [comment]
Where can one learn what that `extra._hash` does on Composer config?
To me it seem the has of the current `date`.
But what is it for??

**Comment by lucatume** [comment]
> Where can one learn what that `extra._hash` does in Composer config?
> To me it seem the hash of the current `date`.
> But what is it for??

I used it to bump the `composer.json` file contents in a non-meaningful way and get the CI caches to refresh.

**Comment by szepeviktor** [comment]
I suggest you a field defined by Composer schema. For example `time`
https://getcomposer.org/doc/04-schema.md#time

**Comment by szepeviktor** [comment]
Actually `gerbal/always-cache` is highly dangerous ☣️ as it caches failed builds/runs.
Please use `actions/cache` with a `key` that contains the information you need.

But if your goal is to delete cache entries

> Users with write access to a repository can use the GitHub web interface to delete cache entries.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#deleting-cache-entries

or you could use the `gh actions-cache delete ...` command locally.

**Comment by lucatume** [comment]
> Actually `gerbal/always-cache` is highly dangerous ☣️ as it caches failed builds/runs. Please use `actions/cache` with a `key` that contains the information you need.
> 
> But if your goal is to delete cache entries
> 
> > Users with write access to a repository can use the GitHub web interface to delete cache entries.
> 
> https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#deleting-cache-entries
> 
> or you could use the `gh actions-cache delete ...` command locally.

I know all of that now, I did not know at the time; it will be something else to clean up.

**Comment by XedinUnknown** [comment]
Thanks! 🙏

**Pull request merged**
