### PR TITLE
Fix/459 haveplugin

### PR DESCRIPTION
**Pull request by Luc45**
Fixes https://github.com/lucatume/wp-browser/issues/459

Essentially, it adapts `havePlugin` to be able to handle single-file plugins such as `foo.php`, cleaning up just the created file afterward. The old implementation of `havePlugin` supported only a plugin inside a folder: `foo/bar.php`.

I didn't go into making it also compatible with deeper tree structures such as `foo/bar/baz.php` as discussed on the issue https://github.com/lucatume/wp-browser/issues/459, because `havePlugin` creates a PHP file with a plugin header and contents. In WordPress, a plugin entry-file can be either a `wp-content/plugins/foo.php` or `wp-content/plugins/foo/bar.php`, never `wp-content/plugins/foo/bar/baz.php`.

Therefore I think this scenario doesn't fit the `havePlugin` function, but perhaps could be viable for a new function: `haveFileInPlugin($plugin_folder, $filename, $file_contents)`. Let me know if you think otherwise, and I can adapt this PR.

I've checked `haveMuPlugin()` as well and there was no need for modifications there, as it allows only single-files, which is fine due to the nature of mu-plugins.

### CODE REVIEW

**Comment by Luc45** [comment]
CI: https://github.com/Luc45/wp-browser/runs/1271612571

**Comment by Luc45** [comment]
The failing test doesn't seem related to my changes. Maybe UOPZ is not available in the 5.6 docker image?

**Comment by Luc45** [comment]
It skips that test locally because `uopz` is not available, using the PHP image `lucatume/codeception-php-5.6`.

This is the same PHP image used both by `make dev` and `make test_56`, which is the command that the workflow runs.

image

I'm not sure why that test is not being skipped on CI 5.6, if `uopz` is indeed not loaded.

Let me know if I can help with this.

**Comment by lucatume** [comment]
Please, pull the very latest version of the image from Dockerhub, due to some merge issues, the image that was up, for about a day, had *not* the `uopz` extension installed.

[All should be fine now](https://hub.docker.com/layers/lucatume/codeception-php-5.6/latest/images/sha256-5af8c9f516673a33df810d7af691d8fddbbca0b63bb8e6a4060e1334f63ec6c6?context=repo)

**Comment by Luc45** [comment]
@lucatume I've pulled the latest image and now I've got UOPZ on my local machine.

This is looking like a UOPZ bug on PHP 5.6 to me, as it works fine in PHP 7.3.

**Comment by Luc45** [comment]
https://pecl.php.net/package-changelog.php?package=uopz

```
PHP 5.6.40 (cli) (built: Jan 23 2019 00:04:26) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with uopz v2.0.7, Copyright (c) 2014, by Joe Watkins <krakjoe@php.net>
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

```
PHP 7.3.8 (cli) (built: Aug 14 2019 08:01:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
```

PHP 7.3 doesn't output `uopz` version with `php --version`, but I can see that it is enabled by running a few commands:

```
/project > php --ri uopz               

uopz

uopz support => enabled
Version => 6.1.2
```

From `uopz` 2.0.7 to 6.1.2 there were 2 fixes to constant redefine in the changelog. It's probably it.

**Comment by Luc45** [comment]
image

Running `cr unit Codeception/Module/WPLoaderTest.php` on 7.3 passes - does not skip nor fail.

**Comment by Luc45** [comment]
Lastly, this shouldn't have anything to do with the changes introduced in this PR.

**Pull request merged**
