### PR TITLE
Implemented getInternalDomains() method

### PR DESCRIPTION
**Pull request by kmbt**
Implemented getInternalDomains() method
in: src/Codeception/Module/WordPress.php

Also, fixed parsing the path for host other than localhost in:
src/tad/WPBrowser/Connector/WordPress.php

### CODE REVIEW

**Comment by kmbt** [comment]
Oh, the build is failing. As I am quite new to Github, could someone please give me a hint on what I have done wrong? :)

**Comment by kmbt** [comment]
As I had trouble with setting up a test environment on my own please double-check if this PR does not break anything :)

**Comment by lucatume** [comment]
Problem is this PR changes nothing! You probably want to re-instate the methods reverted in the second commit.

Also: could you elaborate on the objective of the code? Could you make an example of how, when and where the method would be used?

**Comment by lucatume** [comment]
Ok, got on track for this and looking into the code you proposed.

**Pull request merged**
