### PR TITLE
Update wp browser commons

### PR DESCRIPTION
**Pull request by abenevaut**
Update `lucatume/wp-browser-commons` to `1.2.9`. No change to apply this update, the `composer.json` is correctly set to `^1.2.5`.

- I removed the `composer.lock` that sound like a bad practice (added it to the `.gitignore` file)
    - I saw `lucatume/wp-browser-commons` fixed to a revision in the `composer.lock`, I guess that could occur trouble if the vendor user need to adapt the revision with his project constraints.

### CODE REVIEW

**Comment by abenevaut** [comment]
@lucatume PR ready for review 👍

**Comment by lucatume** [comment]
Hi there, thanks for the PR, since the version of `wp-browser-commons` is not locked but just set to a minimum level the latest one will be installed.
The `composer.lock` file [will not affect projects that use wp-browser](https://getcomposer.org/doc/02-libraries.md#lock-file) as only the root `composer.lock` file, the one from the project using `wp-browser` will be taken into account.

So: what problem are you trying to solve here? I ask as the files you modified are not related directly to `wp-browser` but rely on Composer base functions.

Let me know.

**Comment by abenevaut** [comment]
😅 Certainly something i miss understood in vendor management. I was thinking that the `composer.lock` is locking the current revision of `wp-browser-commons` that was why i would PR the deletion of the `composer.lock`. Seems that not the way to go.. So i close the PR.

Thanks for your feedback.

**Comment by lucatume** [comment]
You are welcome and I thank you for your PR anyway.
If you find anything else you find, or that you think could use improvement, PRs are always welcome.

**Pull request closed without merging**
