### PR TITLE
Release 2.5.0

### PR DESCRIPTION
**Pull request by lucatume**
Contains the code from the following PRs by @szepevictor and @Luc45 :

* #378 
* #379 
* #384
* #386
* #387
* #388
* #389

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could you go `@szepevictor` -> @szepeviktor

**Comment by szepeviktor** [comment]
What is that "tad" thing? Is it an abbreviation?

**Comment by Luc45** [comment]
> What is that "tad" thing? Is it an abbreviation?

[TheAverageDev](https://theaveragedev.com/)

**Comment by szepeviktor** [comment]
# 😲

**Pull request closed without merging**
