### PR TITLE
Do not load bootstrap file in WPTestCase

### PR DESCRIPTION
**Pull request by lucatume**
To support running `WPTestCase` methods in a separate process, using the PHPUnit `@runInSeparateProcess` annotation, I've previously hacked together a way of doing it that would rely on the definition of the `PHPUNIT_COMPOSER_INSTALL` constant. This would cause issues when that would be, in turn, doubly defined in the contest static analysis.
This commit refactors that approach into something that should be less destructive, while still relying one some side-effects.

### CODE REVIEW

**Comment by calvinalkan** [comment]
@lucatume Nice, I'll check it tomorrow.

**Comment by calvinalkan** [comment]
https://github.com/symplify/symplify/issues/3938

**Comment by lucatume** [comment]
@calvinalkan not sure what I should look at there. You mention this issue, but not if the fix provided works or not. I see [in the example repo you're not pulling this branch](https://github.com/sniccowp/ecs-wp-browser-bug/blob/master/composer.json#L15), and I see no setting there that would make indicate the `WPTESTCASE_NO_INIT` env var is set when testing things.
Are you suggesting a different approach? I'm considering whether an off-by-default approach would make sense here. I will test this approach in this branch and push.

**Comment by lucatume** [comment]
Ah, I see now there's a deleted comment about another place where there is another issue. Both are related to the support of the `rubInSeparateProcess` annotation.
Ideally, in both instances, I should pick up the env vars set by PHPUnit code that will run the test in a separate process and use those as flags indicating whether that code should execute at all or not. Or set mine, if I'm able to.

**Comment by calvinalkan** [comment]
@lucatume The maintainer of easy-coding-standard was able to track down the fatal error here https://github.com/symplify/symplify/issues/3938#issuecomment-1046045188

Of course, we cant fix wp-browser based on failures in completely unrelated packages but since every static analysis tool uses nikic/php-parser under the hood we should look into this as other tools will probably fail too. ( Im assuming the error is in php-parser, the [exact reason is not clear yet](https://github.com/symplify/symplify/issues/3938#issuecomment-1046065607))

**Comment by lucatume** [comment]
@calvinalkan I've seen the comment and provided, hopefully, a fix for that too in the latest commit.
In both instances, the code is there in shape and form, to support tests running in separate processes. There is no easy way I can think of to detect that kind of environment the way it's set up by PHPUnit.
The initial approach got the job done, but it could use improvement.
If it can be done without disrupting the current support, I have nothing against modifying wp-browser to support whatever quality tool people want to employ. I would like to explore all the options, and I could use some help from your side testing out the fix in this branch, and suggestions if you have any, before deeming it to be something that cannot be done.

**Comment by calvinalkan** [comment]
@lucatume Running my reproducer repo still errors. 

If I'm not completely mistaken trying to handle this in PHP is not going to do anything.

https://github.com/lucatume/wp-browser/pull/564/commits/6e03b1ccd9bd42350f0b12260ae2c2afb438c331#diff-ad16cb1fae78e32703961eefaff28b385ef24921559304daea04e20ad91b8647R27

Defining the constant here will cause the static analyzer (actually the parser probably) to fail. The code in question is never executed. My guess is that redefining the constant here causes a crash in the parser because the file is autoloaded and the constant is already defined. But I could be totally wrong.

**Comment by calvinalkan** [comment]
@lucatume I'm a little confused by the code in question. Why do we need to define this constant here?

**Comment by calvinalkan** [comment]
> 

@lucatume thanks for the explanation, im familiar with the seperate process feature but I cant remember ever having autoloading issues when using it with plain phpunit. Is this somehow related to BC or why will this specifcally not for for the WPTestCase class.

**Comment by lucatume** [comment]
I'm currently out of office, so what follows is a speculation I'll have to confirm looking at the code.
My suspicion is that Codeception, **using** PHPUnit, somehow skips the step where PHPUnit would define the constants used in the separate process feature.

**Comment by lucatume** [comment]
@calvinalkan thanks again for the test repository.
This latest commit did fix it: [asciicast](https://asciinema.org/a/labmUJY4OnFMctiiOVmUlRN2J)

**Comment by calvinalkan** [comment]
@lucatume That's awesome thank you very much. I'm surprised this didn't pop up before. Because both PHP-code sniffer and PHP-code-fixer broke with this.

**Pull request merged**
